# Generated by Django 4.0.1 on 2022-02-02 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.batch'),
        ),
        migrations.AlterField(
            model_name='section',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes.class'),
        ),
    ]
