# Generated by Django 4.0.1 on 2022-02-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_batch_alter_section_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('year',), 'verbose_name_plural': 'batches'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['batch', 'id'], 'verbose_name_plural': 'classes'},
        ),
    ]
