# Generated by Django 4.0.1 on 2022-02-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_batch_alter_section_class_name'),
        ('accounts', '0008_remove_student_roll_no_studentrollno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRollNo',
            new_name='StudentRollNumber',
        ),
    ]
