# Generated by Django 4.0.1 on 2022-02-05 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_studentrollno_studentrollnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
