# Generated by Django 4.0.1 on 2022-02-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_batch_alter_section_class_name'),
        ('accounts', '0010_alter_teacher_joining_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRollNumber',
            new_name='StudentBatchRollNumber',
        ),
    ]
