# Generated by Django 4.0.1 on 2022-02-19 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_studentrollnumber_studentbatchrollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tole',
            field=models.CharField(default='xyz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.CharField(default='xy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ward_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='tole',
            field=models.CharField(default='xy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='village',
            field=models.CharField(default='xy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='ward_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentbatchrollnumber',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_batch_roll_numbers', to='accounts.student'),
        ),
    ]
