# Generated by Django 4.0.1 on 2022-02-02 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('joining_date', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='staffs/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
            ],
        ),
    ]
